name: ipulcay
description: "A new Flutter project."

publish_to: 'none' 

# version: 1.0.8+9 anterior 29/05/2026
# version: 1.0.9+10 actual/en uso 30/05/2026
# version: 1.0.10+11 desarrollo, Subir al storage

version: 1.0.10+11

# Lista de objetivos para la versión 1.0.10+11
# Parchear:
# - Nada por el momento
#
# Nuevas implementaciones:
# - Módulo para generar pedidos mejorar.
# - Guardar dirección escrita.
# - Guardar coordenadas del pedido.
# - Guardar foto referencial opcional.
# - Preparar pedidos para visualización en mapa.

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.12.0
  package_info_plus: ^8.3.1
  firebase_storage: ^13.1.1
  cupertino_icons: ^1.0.8
  cloud_firestore: ^6.4.1
  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  path_provider: ^2.1.5
  image_picker: ^1.2.2
  url_launcher: ^6.3.2
  geolocator: ^14.0.2
  open_filex: ^4.7.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logos/5.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logos/5.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/logos/5.png